import type { EligibilityRule } from '../types/eligibility';

export const ELIGIBILITY_RULES: EligibilityRule[] = [
  { field: "hasValidLicence", failValue: false, severity: "red", consequence: "No valid licence = CLAIM DENIED", category: "Licensing" },
  { field: "correctLicenceClass", failValue: false, severity: "red", consequence: "Wrong licence class for vehicle = CLAIM DENIED", category: "Licensing" },
  { field: "licenceExpired", failValue: true, severity: "red", consequence: "Expired licence = CLAIM DENIED", category: "Licensing" },
  { field: "onSuspension", failValue: true, severity: "red", consequence: "Driving while suspended = CLAIM DENIED + criminal offence", category: "Licensing" },
  { field: "underAlcohol", failValue: true, severity: "red", consequence: "Driving under influence of alcohol = CLAIM DENIED + criminal offence", category: "Driver Fitness" },
  { field: "underDrugs", failValue: true, severity: "red", consequence: "Driving under influence of drugs = CLAIM DENIED + criminal offence", category: "Driver Fitness" },
  { field: "ownerConsent", failValue: false, severity: "red", consequence: "No owner consent = CLAIM DENIED (driving without authorisation)", category: "Ownership" },
  { field: "hasInsurance", failValue: false, severity: "red", consequence: "No insurance = CLAIM DENIED + criminal offence under MV(TPRC) Act", category: "Insurance" },
  { field: "insuranceExpired", failValue: true, severity: "red", consequence: "Expired insurance = CLAIM DENIED + criminal offence", category: "Insurance" },
  { field: "correctUsage", failValue: false, severity: "red", consequence: "Vehicle used outside insured purpose = CLAIM DENIED", category: "Usage" },
  { field: "doingRideHailing", failValue: true, severity: "amber", consequence: "Ride-hailing — ensure you have PHPC/PHV insurance, otherwise claim will be denied", category: "Usage" },
  { field: "pdlWithInstructor", failValue: false, severity: "red", consequence: "PDL holder without instructor = CLAIM DENIED", category: "Licensing" },
  { field: "usingPhone", failValue: true, severity: "amber", consequence: "Phone use = possible denial or contributory negligence", category: "Driver Fitness" },
  { field: "fatigued", failValue: true, severity: "amber", consequence: "Driving while fatigued may constitute negligence", category: "Driver Fitness" },
  { field: "sleepDeprived", failValue: true, severity: "amber", consequence: "Sleep deprivation may constitute negligence", category: "Driver Fitness" },
  { field: "undeclaredMedical", failValue: true, severity: "amber", consequence: "Undeclared medical conditions = possible policy voiding", category: "Driver Fitness" },
  { field: "isNamedDriver", failValue: false, severity: "amber", consequence: "Not a named driver = possible denial or excess surcharge", category: "Insurance" },
  { field: "meetsAgeRequirement", failValue: false, severity: "amber", consequence: "Outside policy age range = possible denial", category: "Insurance" },
  { field: "meetsExperienceRequirement", failValue: false, severity: "amber", consequence: "Below minimum experience = excess surcharge", category: "Insurance" },
  { field: "roadTaxValid", failValue: false, severity: "amber", consequence: "Expired road tax = offence (may not void claim but complicates it)", category: "Vehicle Compliance" },
  { field: "inspectionPassed", failValue: false, severity: "amber", consequence: "Failed/missed vehicle inspection = possible issue", category: "Vehicle Compliance" },
  { field: "unauthorisedMods", failValue: true, severity: "amber", consequence: "Undeclared modifications = possible claim denial", category: "Vehicle Compliance" },
  { field: "tyresLegal", failValue: false, severity: "amber", consequence: "Illegal tyre tread depth = offence + contributory negligence", category: "Vehicle Compliance" },
  { field: "exceedingCapacity", failValue: true, severity: "amber", consequence: "Exceeding passenger capacity = negligence", category: "Usage" },
  { field: "doingDelivery", failValue: true, severity: "amber", consequence: "Commercial delivery on private policy may void coverage", category: "Usage" },
  { field: "illegallyParked", failValue: true, severity: "amber", consequence: "Illegal parking may affect liability assessment", category: "Usage" },
  { field: "spectaclesWorn", failValue: false, severity: "amber", consequence: "Spectacles condition not met = possible denial", category: "Licensing" },
];
